# Generated by Django 5.2.1 on 2025-05-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(default=authapp.models.generate_jti, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=authapp.models.default_expires_at)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subject'], name='authapp_jwt_subject_fe3acc_idx'), models.Index(fields=['expires_at'], name='authapp_jwt_expires_d00adb_idx')],
            },
        ),
    ]
